In [68]:
import numpy as np

In [26]:
# matrix
A= [[1,2,3],
   [3,2,1]]
A

[[1, 2, 3], [3, 2, 1]]

In [42]:
A = np.array([1,2,3,3,2,1])
A= A.reshape(2,3)

In [43]:
A.shape

(2, 3)

In [45]:
A.T

array([[1, 3],
       [2, 2],
       [3, 1]])

In [49]:
A= np.array([1,2,1,4,4,5,6,7,7])
A = A.reshape(3,3)
A

array([[1, 2, 1],
       [4, 4, 5],
       [6, 7, 7]])

In [57]:
B = np.linalg.inv(A)
B

array([[-7., -7.,  6.],
       [ 2.,  1., -1.],
       [ 4.,  5., -4.]])

In [55]:
np.dot(A,B)

array([[  1.00000000e+00,  -1.77635684e-15,   8.88178420e-16],
       [ -2.22044605e-15,   1.00000000e+00,   4.44089210e-15],
       [  7.54951657e-15,  -1.77635684e-15,   1.00000000e+00]])

In [25]:
B =[[0,2], [1, -1], [0,1]]
B

[[0, 2], [1, -1], [0, 1]]

In [35]:
C = np.eye(5)
C

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [36]:
#Identity matrix dimension
C.shape

(5, 5)

Write a program that takes an integer as an input, then checks if
that number is 10 or more. If so, print out that the number is a
multiple-digit number, otherwise, print out that it is single-digit and on a separate line, print the number.

In [67]:
y = input("Enter and integer: ")
if (int(y) > 10):
    print(y + " is a multiple-digit number")
else:
    print("Single-digit \n" + y)

Enter and integer: 4
Single-digit 
4


In [71]:
grocery = ['bread', 'eggs', 'sugar', 'chocolate', 'honey']
grocery[2]

'sugar'

Using a list of five grocery items, print out each item on its own
line using a for loop.


In [86]:
for x in grocery:
    print(x)


bread
eggs
sugar
chocolate
honey


In [85]:
name="Mandela"
name[4]

'e'

In [89]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

Create a 2x3x2 array in a variable containing ones in every element.
Print the variable.

In [98]:
C = np.ones((2,3,2))
C

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [99]:
C.ndim

3

Create a 3x3 array matching the matrix $\left[\begin{array}{ccc}
1 & 2 & 3 \\ 4 & 5 & 6 \\ 7& 8& 9\end{array}\right] $. Print the element from the intersection of the 2nd row and 3rd column.

In [102]:
D = np.array([[1,2,3], [4,5,6], [7,8,9]])
D


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
D[1,2]

6

In [109]:
D**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])